def init():
    global BULLET_SPEED
    BULLET_SPEED = 6
    global BULLET_RADIUS
    BULLET_RADIUS = 10
    
    global ENEMY_COOLDOWN
    ENEMY_COOLDOWN = 100
    global ENEMY_MAX_COUNT
    ENEMY_MAX_COUNT = 1
    global ENEMY_RADIUS
    ENEMY_RADIUS = 30
    global ENEMY_SPEED
    ENEMY_SPEED = 1
  

    global PLAYER_COOLDOWN
    PLAYER_COOLDOWN = 30
    global PLAYER_SPEED
    PLAYER_SPEED = 4
    global PLAYER_RADIUS
    PLAYER_RADIUS = 25

    global WINDOW_WIDTH
    WINDOW_WIDTH = 600
    global WINDOW_HEIGHT
    WINDOW_HEIGHT = 800
    global WINDOW_FPS
    WINDOW_FPS = 60
    global WINDOW_VOLUME
    WINDOW_VOLUME = .1
    global WINDOW_WIN_SCORE
    WINDOW_WIN_SCORE = 5